on:
  push:
    branches:
      - v3-beta
  pull_request:
name: Test
jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    - name: Fetch Repository
      uses: actions/checkout@v3
    - name: Run Test
      run: go test ./... -v -race
